databases:
  - name: web-table-exam-db
    databaseName: web_table_exam
    user: web_table_exam_user
    plan: free

services:
  - type: web
    name: web-table-exam-api
    runtime: node
    rootDir: backend
    plan: free
    buildCommand: npm install
    preDeployCommand: npm run seed
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: DB_CLIENT
        value: postgres
      - key: DATABASE_URL
        fromDatabase:
          name: web-table-exam-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: FRONTEND_URL
        value: https://web-table-exam-frontend.onrender.com
      - key: SUPERADMIN_EMAIL
        value: erbol.abdusatov@alatoo.edu.kg
      - key: SUPERADMIN_NAME
        value: Erbol Abdusatov
  - type: web
    name: web-table-exam-frontend
    runtime: static
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    pullRequestPreviewsEnabled: false
    envVars:
      - key: VITE_API_BASE_URL
        value: https://web-table-exam-api.onrender.com/api
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
